@extends('layouts.app')

@section('title', 'Data Science Services')

@section('meta_description', 'This is a brief description of the home page for SEO purposes.')

@section('meta_keywords', 'laravel, home, keywords')

@section('content')
<!-- Abvout Start -->
<div class="container-fluid about hero__banner__tech py-5" style="background: url('{{ asset('assets/web/tech__background.webp') }}'); background-repeat:no-repeat; background-size:cover;">
 <div class="container py-5">
  <div class="row g-5 align-items-center" data-aos="fade-up" data-aos-delay="100">
   <div class="col-xl-7 wow fadeInLeft">
    <div>
     <!-- <h4 class="text-primary1">About Us</h4> -->
     <h1 class="display-5 mb-4 text-white">Data Science Services</h1>
     <p class="mb-4 text-white">Create quality apps with Data Science to ensure your apps performs at a higher scale
     </p>
    </div>
   </div>
   <div class="col-xl-5 wow fadeInRight" data-wow-delay="0.2s">
    <div class=" rounded position-relative overflow-hidden  d-flex justify-content-center">
     <img src="{{ asset('assets/web/data-science.webp') }}" class="img-fluid rounded w-100 image-with-shadow" alt="">
     <!-- <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script><lottie-player src="https://lottie.host/c7bfe87d-3ff6-4393-a188-2e75c4e054f6/K6w0F2mLOc.json" background="#fff" speed="1" style="width: 100%; height: 400px" loop autoplay direction="1" mode="normal"></lottie-player> -->
    </div>
   </div>
  </div>
 </div>
</div>
<div class="container-fluid about py-5">
 <div class="container py-5">

  <div class="text-center mx-auto pb-5 wow fadeInUp" data-aos="fade-up" data-aos-delay="100" style="max-width: 800px;">
   <h2 class="display-5 mb-4">Data Science Consulting Services</h2>
   <p class="mb-4">Connects the dots between the business world and the data world using Data Science Services</p>
  </div>
  <div class="row g-5 align-items-center" data-aos="fade-up" data-aos-delay="100">
   <div class="col-xl-6 wow fadeInLeft">
    <div>
     <!-- <h4 class="text-primary1">About Us</h4> -->
     <!-- <p class="mb-4 fw-bold fs-3">What is Laravel Web Development ?</p> -->
     <p class="mb-4">There is no denying in the fact that digitalization has taken over the world in aspects. The amount of data generated by digitalization is growing exponentially; therefore, businesses are facing challenges in managing this massive amount of data and are seeking best practices to handle data meaningfully.</p>
     <p class="mb-4">Nettechnocrats, help business solve this big data problem and gain a competitive edge using this information, Data Science has come into play. We extract useful information by analyzing this massive amount of data using automated methods. Thus, bridge the gap between data and decision by studying this massive information, where it comes from, what it represents and how to turn it into valuable resources.</p>

     <a href="#" class="btn btn-primary rounded-pill py-3 px-5 flex-shrink-0">Contact Us</a>
    </div>
   </div>
   <div class="col-xl-6 wow fadeInRight" data-wow-delay="0.2s">
    <div class="rounded position-relative overflow-hidden">
     <img src="{{ asset('assets/web/datascience.webp') }}" class="img-fluid rounded w-100 image-with-shadow" alt="">

    </div>
   </div>
  </div>
  <p class="mt-3">With our expertise and experience of working with various data visualization and analytics tools like Tableau, SAS, R, QlikView, QlikSense, IBM Cognos, Azure ML and more, is the main reason behind our popularity as leading Data Analytics Service Providers.</p>
 </div>
</div>
<!-- About End -->

<!-- Services Start -->
<div class="container-fluid service pb-5">
 <div class="container pb-5">
  <h2 class="display-5 mb-4 text-center">Our Data Analytics Services Offering</h2>
  <p class="mb-4 text-center">As one of the leading Data Analytics Service Providers, we at Nettechnocrats solve complex data analytic challenges with appropriate technology tools and processes to achieve the strategic objectives. With our team of experts, we offer our clients with neutral recommendations that are tailored to their current technology objective, landscape and preferences.</p>
  <div class="row g-4">
   <div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="0.2s">
    <div class="service-item">
     <div class="service-img">
      <i class="fa-solid fa-magnifying-glass-chart"></i>
     </div>
     <div class="rounded-bottom p-4">
      <a href="#" class="h4 d-inline-block mb-4">
       DATA ANALYTICS
      </a>
      <p class="mb-4">Our team of proficient data analysts helps in delivering effective, scalable, & high-quality big data applications by studying customer behaviour and market trends.</p>
      <!-- <a class="btn btn-primary rounded-pill py-2 px-4" href="#">Learn More</a> -->
     </div>
    </div>
   </div>
   <div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="0.4s">
    <div class="service-item">
     <div class="service-img">
      <i class="fa-solid fa-tachograph-digital"></i>
     </div>
     <div class="rounded-bottom p-4">
      <a href="#" class="h4 d-inline-block mb-4">DATA MANAGEMENT</a>
      <p class="mb-4">We ensure the authenticity and integrity of your data by preventing any unauthorized data tampering and make informed decisions.</p>
      <!-- <a class="btn btn-primary rounded-pill py-2 px-4" href="#">Learn More</a> -->
     </div>
    </div>
   </div>
   <div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="0.6s">
    <div class="service-item">
     <div class="service-img">
      <i class="fa-solid fa-database"></i>
     </div>
     <div class="rounded-bottom p-4">
      <a href="#" class="h4 d-inline-block mb-4">DATA WAREHOUSING</a>
      <p class="mb-4">To help clients enhance and maintain their data warehouses our data architecture experts augment the analytical capabilities for improved performance.</p>
      <!-- <a class="btn btn-primary rounded-pill py-2 px-4" href="#">Learn More</a> -->
     </div>
    </div>
   </div>
   <div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="0.2s">
    <div class="service-item">
     <div class="service-img">
      <i class="fa-solid fa-chart-line"></i>
     </div>
     <div class="rounded-bottom p-4">
      <a href="#" class="h4 d-inline-block mb-4">ADVANCE DATA VISUALISATION</a>
      <p class="mb-4">Get real-time trend analysis and accurate data evaluation by leveraging the advantage of graphs, charts & dashboards and get better insights into advanced & complex data.</p>
     </div>
    </div>
   </div>
   <div class="col-md-6 col-lg-4 wow fadeInUp" data-wow-delay="0.4s">
    <div class="service-item">
     <div class="service-img">
      <i class="fa-brands fa-creative-commons-remix"></i>
     </div>
     <div class="rounded-bottom p-4">
      <a href="#" class="h4 d-inline-block mb-4">DATA CONSULTATION SERVICES</a>
      <p class="mb-4">To help clients opt the right analytics platform, our big data consultants evaluate trends & technology in order to provide state of art services.</p>
     </div>
    </div>
   </div>
  </div>
 </div>
</div>
<!-- Services End -->

<section class="light-background why__choose__Net">
 <div class="container">
  <h2>Why Nettechnocrats for Data Analytics Services?</h2>
  <p class="pb-4 pt-4">Businesses are tremendously driving positive outcomes for themselves and their customers, with data and analytics, while maintaining and facilitating the highest level of data protection.</p>
  <div class="row pt-2">
   <div class="col-lg-6 position-relative align-self-start " data-aos="fade-up" data-aos-delay="100">
    <div class="row mt-3">
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="200">5+ years of average experience
      </p>
     </div>
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="200">On time project delivery guaranteed
      </p>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="300">High sealed security
      </p>
     </div>
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="300">Dedicated Project Managers
      </p>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="400">24*7 Support
      </p>
     </div>
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="400">Hassle free communication
      </p>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="500">Maintenance Service
      </p>
     </div>
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="500">User-Friendly Data Structure
      </p>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="700">Integrity & transparency
      </p>
     </div>
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="700">Free no-obligation quote
      </p>
     </div>
    </div>
    <div class="row">
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="800">Flexible Engagement Models
      </p>
     </div>
     <div class="col-lg-6">
      <p class="why__answer" data-aos="fade-up" data-aos-delay="800">Non-Discloser Agreement
      </p>
     </div>
    </div>
   </div>
   <div class="col-lg-6 content d-flex align-items-center" data-aos="fade-up" data-aos-delay="200">
    <div class="seo__animation__gifs">
     <div class="rounded position-relative overflow-hidden">
      <img src="{{ asset('assets/web/datascience-nettechnocrats.webp') }}" class="img-fluid rounded w-100 image-with-shadow" alt="">

     </div>
    </div>
   </div>
  </div>
 </div>
</section>

<!--  -->

<section class="brand__images py-4">
 <div class="container">
  <h3 class="text-center">Count On Our Passion For Technology</h3>
  <p class="text-center">Since 2011, we have been going that extra mile to create exceptional digital strategies for our clients and their customers. That said, we are awarded by top-tier research firms and featured in premium magazines and journals.</p>
  <div class="img__row">
   <div class="brands"><img src="{{ asset('assets/web/common-img/Coca-Cola.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/5-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/7-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/8-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/9-1.webp') }}" alt="" srcset=""></div>
  </div>
  <div class="img__row">
   <div class="brands"><img src="{{ asset('assets/web/common-img/10-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/11-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/bjp-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/bubble.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/chemists-world.webp') }}" alt="" srcset=""></div>
  </div>
  <div class="img__row">
   <div class="brands"><img src="{{ asset('assets/web/common-img/dbl-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/omni-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/Preapps.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/tolo-1.webp') }}" alt="" srcset=""></div>
   <div class="brands"><img src="{{ asset('assets/web/common-img/1-1.webp') }}" alt="" srcset=""></div>
  </div>
 </div>
</section>

<!-- Call To Action Section -->
<section id="call-to-action" class="call-to-action section accent-background">

 <div class="container">
  <div class="row justify-content-center" data-aos="zoom-in" data-aos-delay="100">
   <div class="col-xl-10">
    <div class="text-center">
     <h3>Ready To Get Started?</h3>
     <p>Stay ahead from Crowd. We have an expert team of application developers who are experienced and proficient. We have good experience in bespoke web and mobile app development and are committed to delivering the best of the class solutions.</p>
     <a class="cta-btn" href="#">Contact Us</a>
    </div>
   </div>
  </div>
 </div>

</section><!-- /Call To Action Section -->


@endsection